nome = str(input('Digite seu nome completo: '))
M = nome.upper()
m = nome.lower()
letras = len(nome.strip()) - nome.count(' ')
P = nome.split()
LP = nome.find(' ')
print('Analisando seu nome...')
print('Seu nome em maiúsculas é {}'.format(M))
print('Seu nome em minúsculas é {}'.format(m))
print('Seu nome tem ao todo {} letras'.format(letras))
print('Seu primeiro nome é {} e ele tem {} letras.'.format(P[0], LP ))